* Patched patches
- dwm-6.0-autostart.diff
  + This patch will make dwm run "~/.dwm/autostart_blocking.sh" and "~/.dwm/autostart.sh &" before entering the handler loop.
- dwm-actualfullscreen-20191112-cb3f58a.diff
  + Actually toggle fullscreen for a window, instead of toggling the status bar and the monocle layout.
- dwm-center-6.2.diff
  + This patch starts program in the center of the current screen
- dwm-deck-6.2.diff
  + this patch adds 2 pane layout
- dwm-deck-tilegap-6.1.diff
  + this patch adds gaps for the 2 pane layout
- dwm-floatpos-6.2.diff
  + This patch makes floating rules  patch work using relative coordinates on multi monitor setup
- dwm-fullgaps-6.2.diff
  + This patch adds gaps between client windows.
- dwm-hide_vacant_tags-6.2.diff
  + This patch prevents dwm from drawing tags with no clients (i.e. vacant) on the bar.
- dwm-pertag-20170513-ceac8c9.diff
  + This patch enables one layout per tag in contrast of one layout for all tags.
- dwm-push.20201112-61bb8c870.diff
  + pushup and pushdown provide a way to move clients inside the clients list.
- dwm-savefloats-20181212-b69c870.diff
  + This patch saves size and position of every floating window before it is forced into tiled mode. If the window is made floating again, the old dimensions will be restored.
- dwm-scratchpad-6.2.diff
  + The scratchpad patch allows you to spawn or restore a floating terminal window. It is usually useful to have one to do some short typing.
- dwm-single-tagset-6.2.diff
  + This patch lets you have same tagset on multiple monitors
- dwm-showselmon-6.2.diff
  + Shows which monitor is currently selected. Unselected monitors now use inverted colors in status bar.
- dwm-statusallmons-6.2.diff
  + This patch draws and updates the statusbar on all monitors.
- dwm-statuscmd-signal-6.2.diff
  + This patch adds the ability to execute shell commands based on the mouse button and position when clicking the status bar.
- dwm-tagswapmon-6.2.diff
  + This patch enables swapping all windows between monitors
- dwm-warp-6.2.diff
  + This patch warps the mouse cursor to the center of the currently focused window
